apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
replicas:
- count: 1
  name: deployment1
- count: 1
  name: deployment2
images:
- name: 210217920752.dkr.ecr.us-east-2.amazonaws.com/eks-sample-test-sample-app
  newTag: 288e92fdb1d5e268eb7c7c810a073f4f457ba482
